# Generated by Django 5.0.1 on 2024-03-10 12:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('film_title', models.CharField(max_length=128)),
                ('film_description', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'films',
            },
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_photo', models.ImageField(blank=True, upload_to='Images/')),
                ('img_title', models.CharField(max_length=128)),
                ('img_description', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Photography',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_photo', models.ImageField(blank=True, upload_to='images/')),
                ('st_title', models.CharField(max_length=128)),
                ('st_description', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
